USE [master]
GO

/****** Object:  Database [Starter]    Script Date: 23/11/2017 20:44:37 ******/
CREATE DATABASE [Starter]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Starter', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Starter.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Starter_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Starter_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Starter] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Starter].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Starter] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Starter] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Starter] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Starter] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Starter] SET ARITHABORT OFF 
GO

ALTER DATABASE [Starter] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Starter] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Starter] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Starter] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Starter] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Starter] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Starter] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Starter] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Starter] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Starter] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Starter] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Starter] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Starter] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Starter] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Starter] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Starter] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Starter] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Starter] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Starter] SET  MULTI_USER 
GO

ALTER DATABASE [Starter] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Starter] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Starter] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Starter] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Starter] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Starter] SET  READ_WRITE 
GO

