USE [master]
GO

/****** Object:  Database [Obligatorio2]    Script Date: 28/10/2017 17:37:45 ******/
CREATE DATABASE [Obligatorio2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Obligatorio2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Obligatorio2.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Obligatorio2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Obligatorio2_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Obligatorio2] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Obligatorio2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Obligatorio2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Obligatorio2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Obligatorio2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Obligatorio2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Obligatorio2] SET ARITHABORT OFF 
GO

ALTER DATABASE [Obligatorio2] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Obligatorio2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Obligatorio2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Obligatorio2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Obligatorio2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Obligatorio2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Obligatorio2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Obligatorio2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Obligatorio2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Obligatorio2] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Obligatorio2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Obligatorio2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Obligatorio2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Obligatorio2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Obligatorio2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Obligatorio2] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Obligatorio2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Obligatorio2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Obligatorio2] SET  MULTI_USER 
GO

ALTER DATABASE [Obligatorio2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Obligatorio2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Obligatorio2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Obligatorio2] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Obligatorio2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Obligatorio2] SET  READ_WRITE 
GO

